/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pe.edu.unprg.view;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.unprg.controller.ProveedorJpaController;
import pe.edu.unprg.entity.Proveedor;

/**
 *
 * @author asus
 */
public class ProveedorF extends javax.swing.JInternalFrame {

    //generar variables 
    private ProveedorJpaController cjc = new ProveedorJpaController();
    private DefaultTableModel model;
    private List<Proveedor> lista;
    private Proveedor proveedor = new Proveedor();
    private String accion = "";
            
    /**
     * Creates new form Proveedor
     */
    public ProveedorF() {
        initComponents();
        Listar();
        disableForm();
         //para que ocupe todo el maximo de la pantalla
        
        
    }
    
    //metodo 
    private void disableForm(){
        btnGUARDAR.setEnabled(false);
        btnCANCELAR.setEnabled(false);
        btnNUEVO.setEnabled(true);
        btnEDITAR.setEnabled(true);
        btnELIMINAR.setEnabled(true);
        txtID.setEnabled(false);
        txtNOMBRE.setText("");
        txtRUC.setText("");
        txtDIRECCION.setText("");
        txtTELEFONO.setText("");
        txtBORRADOR.setText("1");
        txtBORRADOR.setEnabled(true);
    }
    
    //
    private void enableForm(){
        btnGUARDAR.setEnabled(true);
        btnCANCELAR.setEnabled(true);
        btnNUEVO.setEnabled(false);
        btnEDITAR.setEnabled(false);
        btnELIMINAR.setEnabled(false);
        
    }
    
    
    
    //mostrar datos en la tabla (crando un metodo listar)
    private void Listar() {
        model = (DefaultTableModel) tbDATOS.getModel();
        if (model.getRowCount() > 0) {
            model.setNumRows(0);
        }
        Object[] obj = new Object[6];
        try {
            lista = cjc.findProveedorEntities();
            for (int i = 0; i < lista.size(); i++) {
                proveedor = (Proveedor) lista.get(i);
                obj[0] = proveedor.getIdProveedor();
                obj[1] = proveedor.getNombre();
                obj[2] = proveedor.getRuc();
                obj[3] = proveedor.getDireccion();
                obj[4] = proveedor.getTelefono();
                obj[5] = proveedor.getBorrado().equals("1") ? "Activo" : "Inactivo"; 
                model.addRow(obj);
            }
            tbDATOS.setModel(model);
        }catch (Exception e){
            JOptionPane.showConfirmDialog(null, "Error en el sistema", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNOMBRE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDIRECCION = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTELEFONO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBORRADOR = new javax.swing.JTextField();
        btnGUARDAR = new javax.swing.JButton();
        btnCANCELAR = new javax.swing.JButton();
        btnELIMINAR = new javax.swing.JButton();
        btnEDITAR = new javax.swing.JButton();
        btnNUEVO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDATOS = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Proveedor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SISTEMA DE PROVEEDORES");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 337, 37));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setText("ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtID.setBackground(new java.awt.Color(204, 204, 204));
        txtID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 25));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        txtNOMBRE.setBackground(new java.awt.Color(204, 204, 204));
        txtNOMBRE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 130, 25));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setText("RUC :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtRUC.setBackground(new java.awt.Color(204, 204, 204));
        txtRUC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 130, 25));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setText("DIRECCION :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        txtDIRECCION.setBackground(new java.awt.Color(204, 204, 204));
        txtDIRECCION.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtDIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 130, 25));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setText("TELEFONO :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        txtTELEFONO.setBackground(new java.awt.Color(204, 204, 204));
        txtTELEFONO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, 25));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setText("BORRADO :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        txtBORRADOR.setBackground(new java.awt.Color(204, 204, 204));
        txtBORRADOR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtBORRADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 130, 25));

        btnGUARDAR.setBackground(new java.awt.Color(153, 255, 204));
        btnGUARDAR.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnGUARDAR.setText("GUARDAR");
        btnGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(btnGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 94, 33));

        btnCANCELAR.setBackground(new java.awt.Color(153, 255, 204));
        btnCANCELAR.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnCANCELAR.setText("CANCELAR");
        btnCANCELAR.setMaximumSize(new java.awt.Dimension(84, 23));
        btnCANCELAR.setMinimumSize(new java.awt.Dimension(84, 23));
        btnCANCELAR.setPreferredSize(new java.awt.Dimension(84, 23));
        btnCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELARActionPerformed(evt);
            }
        });
        getContentPane().add(btnCANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 94, 33));

        btnELIMINAR.setBackground(new java.awt.Color(153, 255, 204));
        btnELIMINAR.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnELIMINAR.setText("ELIMINAR");
        btnELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnELIMINARActionPerformed(evt);
            }
        });
        getContentPane().add(btnELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));

        btnEDITAR.setBackground(new java.awt.Color(153, 255, 204));
        btnEDITAR.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnEDITAR.setText("EDITAR");
        btnEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITARActionPerformed(evt);
            }
        });
        getContentPane().add(btnEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 80, -1));

        btnNUEVO.setBackground(new java.awt.Color(153, 255, 204));
        btnNUEVO.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnNUEVO.setText("NUEVO");
        btnNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(btnNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 80, -1));

        tbDATOS.setBackground(new java.awt.Color(204, 204, 204));
        tbDATOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        tbDATOS.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        tbDATOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "RUC", "DIRECCION", "TELEFONO", "BORRADOR"
            }
        ));
        tbDATOS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbDATOS.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tbDATOS.setShowGrid(true);
        tbDATOS.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tbDATOS);
        tbDATOS.getAccessibleContext().setAccessibleName("");
        tbDATOS.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 570, 107));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/unprg/images/fondo10.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNUEVOActionPerformed
        // TODO add your handling code here:
        //boton nuevo
        enableForm();
        accion = "Agregar";
        
    }//GEN-LAST:event_btnNUEVOActionPerformed

    private void btnGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUARDARActionPerformed
        // TODO add your handling code here:
        //para guardar
        try{
           Proveedor proveedor = new Proveedor();
           proveedor.setNombre(txtNOMBRE.getText());
           proveedor.setRuc(txtRUC.getText());
           proveedor.setDireccion(txtDIRECCION.getText());
           proveedor.setTelefono(txtTELEFONO.getText());
           proveedor.setBorrado(txtBORRADOR.getText());
           int RSP = 0;
           switch (accion){
               case "Agregar":
                   cjc.create(proveedor);
                   RSP =1;
                   break;
               case "Editar":
                   proveedor.setIdProveedor(Integer.parseInt(txtID.getText()));
                   proveedor.setCompraList(cjc.findProveedor(Integer.parseInt(txtID.getText())).getCompraList());
                   cjc.edit(proveedor);
                   RSP =1;
                   break;
               default:
                   JOptionPane.showConfirmDialog(null, "Accion no encontrada", "Advertencia", JOptionPane.WARNING_MESSAGE);
               
           }
            if (RSP ==1) {
                JOptionPane.showConfirmDialog(null, "Operacion corectamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                Listar();
                disableForm();
            }
        }catch (Exception e){
            JOptionPane.showConfirmDialog(null, "Error en el sistema", "Advertencia", JOptionPane.WARNING_MESSAGE);          
        }
    }//GEN-LAST:event_btnGUARDARActionPerformed

    private void btnEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITARActionPerformed
        //EDITAR
        
        if (tbDATOS.getSelectedRowCount() == 1) {
            try{
                this.accion = "Editar";
                enableForm();
                int row = tbDATOS.getSelectedRow(); //numero de fila que se esta seleccionando
                txtID.setText(tbDATOS.getValueAt(row, 0).toString());
                //crear un nuevo proveedor
                Proveedor proveedor = new Proveedor(); // 
                proveedor = cjc.findProveedor(Integer.parseInt(txtID.getText())); //para traer el id
                txtNOMBRE.setText(proveedor.getNombre());
                txtRUC.setText(proveedor.getRuc());
                txtDIRECCION.setText(proveedor.getDireccion());
                txtTELEFONO.setText(proveedor.getTelefono());
                txtBORRADOR.setText(proveedor.getBorrado());  
                txtNOMBRE.requestFocus(); //para que el cursor ese en la caja de texto 
            }catch (Exception e){
              JOptionPane.showMessageDialog(null, "Seleccionar", "Advertencia", JOptionPane.WARNING_MESSAGE);  
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);  
        } 
            
    }//GEN-LAST:event_btnEDITARActionPerformed

    private void btnCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELARActionPerformed
        //cancelar
        disableForm();
    }//GEN-LAST:event_btnCANCELARActionPerformed

    private void btnELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnELIMINARActionPerformed
        //eliminar
         if (tbDATOS.getSelectedRowCount() == 1) {
            try{
                
                int row = tbDATOS.getSelectedRow(); //numero de fila que se esta seleccionando
                int id = Integer.parseInt(tbDATOS.getValueAt(row,0).toString());
                String nombre = tbDATOS.getValueAt(row, 2).toString();
                txtID.setText(tbDATOS.getValueAt(row, 0).toString());
                if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea Eliminar " +nombre + "?")==JOptionPane.YES_OPTION) {
                    cjc.destroy(id);
                    JOptionPane.showMessageDialog(null, "Operacion realizada correctamente", "Informacion", JOptionPane.WARNING_MESSAGE);
                    Listar();
                }
               
               
            }catch (Exception e){
              JOptionPane.showMessageDialog(null, "Seleccionar", "Advertencia", JOptionPane.WARNING_MESSAGE);  
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);  
        } 
            
    }//GEN-LAST:event_btnELIMINARActionPerformed

    public void CentrarVentana(JInternalFrame frame){
        jLabel8.add(frame);
        
        Dimension dimension = jLabel8.getSize();
        Dimension dimensionIF = frame.getSize();
        frame.setLocation((dimension.width - dimensionIF.height)/2, (dimension.height - dimensionIF.width)/2);
        frame.show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCANCELAR;
    private javax.swing.JButton btnEDITAR;
    private javax.swing.JButton btnELIMINAR;
    private javax.swing.JButton btnGUARDAR;
    private javax.swing.JButton btnNUEVO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDATOS;
    private javax.swing.JTextField txtBORRADOR;
    private javax.swing.JTextField txtDIRECCION;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtTELEFONO;
    // End of variables declaration//GEN-END:variables
}
